### ISSUE TITLE
Cloudflare - 'yarn build' failing on fresh install

### ISSUE THREAD

**Issue by bradyhigginbotham** [remix-run/react-router-templates#16]
Not sure where it's attempting to look for css or what may need to be configured as the readme is barebones, but getting the following on a new install when building for production:
```
yarn build
...
vite v5.4.11 building SSR bundle for production...
✓ 42 modules transformed.
x Build failed in 246ms
[vite:css-post] css content for "" was not found
    at Object.renderChunk (file:///Users/bradyhigginbotham/Development/showcase/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36388:19)
    at file:///Users/bradyhigginbotham/Development/showcase/node_modules/rollup/dist/es/shared/node-entry.js:20812:40
    at processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:css-post',
  hook: 'renderChunk'
}
```

**Comment by ieieiei59** [comment]
I added `"node"` to `ssr.resolve.conditions` in `vite.config.ts` and the build succeeded.
However, I don't know much about vite, so I couldn't figure out the exact cause.

my vite.config.ts
```typescript
  // ...
  ssr: {
    target: "webworker",
    noExternal: true,
    resolve: {
      conditions: ["workerd", "browser", "node" /* added this */ ],
    },
    optimizeDeps: {
      include: [
        "react",
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
        "react-dom",
        "react-dom/server",
        "react-router",
      ],
    },
  },
  // ...
```
original vite.config.ts https://github.com/remix-run/react-router-templates/blob/a7fc41042924af24efa9bd3cd2c015ff086ac0eb/cloudflare/vite.config.ts#L21-L37

**Comment by brookslybrand** [comment]
@bradyhigginbotham I was not able to reproduce this issue. I'm using yarn 1.22.22 and was able to build with `yarn build` with no errors. I'm going to close this issue, but if you're still running into this issue please share more details so I can reproduce
